server:
  port: 8081

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/yuan
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
      view:
        prefix: classpath:/templates/
        suffix: .html
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.shenyy.yuan.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql